In [239]:
from flask import Flask,render_template,request,redirect,session

import requests as rq
import simplejson as json
import pandas as pd
import quandl as qd
import numpy as np

from bokeh.plotting import figure, show
from bokeh.embed import components 


app = Flask(__name__)

app.vars={}

In [240]:
app = Flask(__name__)
app.vars={}

In [241]:
@app.route('/symbolpage', methods=['GET'])
def retrievesymbol():
    return render_template('symbolpage.html')
print(app.vars['stocksymbol'])

KeyError: 'stocksymbol'

In [242]:
def retrievestocklinktwo(asymbol):
    mydata = qd.get('WIKI/' + str(asymbol), start_date = '2017-04-01', end_date = '2017-04-30')
    return mydata

In [244]:
df= pd.DataFrame(retrievestocklinktwo('GOOG'))
dfreset = df.reset_index()
dfreset

,Date,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
0,2017-04-03,829.22,840.8500,829.2200,838.550,1671503.0,0.0,1.0,829.22,840.8500,829.2200,838.550,1671503.0
1,2017-04-04,831.36,835.1800,829.0363,834.570,1045363.0,0.0,1.0,831.36,835.1800,829.0363,834.570,1045363.0
2,2017-04-05,835.51,842.4500,830.7200,831.410,1555328.0,0.0,1.0,835.51,842.4500,830.7200,831.410,1555328.0
3,2017-04-06,832.40,836.3900,826.4600,827.880,1254433.0,0.0,1.0,832.40,836.3900,826.4600,827.880,1254433.0
4,2017-04-07,827.96,828.4850,820.5127,824.670,1056692.0,0.0,1.0,827.96,828.4850,820.5127,824.670,1056692.0
5,2017-04-10,825.39,829.3500,823.7700,824.730,978905.0,0.0,1.0,825.39,829.3500,823.7700,824.730,978905.0
6,2017-04-11,824.71,827.4267,817.0201,823.350,1079732.0,0.0,1.0,824.71,827.4267,817.0201,823.350,1079732.0
7,2017-04-12,821.93,826.6600,821.0200,824.320,900480.0,0.0,1.0,821.93,826.6600,821.0200,824.320,900480.0
8,2017-04-13,822.14,826.3800,821.4400,823.560,1122362.0,0.0,1.0,822.14,826.3800,821.4400,823.560,1122362.0
9,2017-04-17,825.01,837.7500,824.4700,837.170,895015.0,0.0,1.0,825.01,837.7500,824.4700,837.170,895015.0
10,2017-04-18,834.22,838.9300,832.7100,836.820,836722.0,0.0,1.0,834.22,838.9300,832.7100,836.820,836722.0
11,2017-04-19,839.79,842.2200,836.2900,838.210,954330.0,0.0,1.0,839.79,842.2200,836.2900,838.210,954330.0
12,2017-04-20,841.44,845.2000,839.3200,841.650,959031.0,0.0,1.0,841.44,845.2000,839.3200,841.650,959031.0
13,2017-04-21,842.88,843.8800,840.6000,843.190,1323583.0,0.0,1.0,842.88,843.8800,840.6000,843.190,1323583.0
14,2017-04-24,851.20,863.4500,849.8600,862.760,1371581.0,0.0,1.0,851.20,863.4500,849.8600,862.760,1371581.0
15,2017-04-25,865.00,875.0000,862.8100,872.300,1654161.0,0.0,1.0,865.00,875.0000,862.8100,872.300,1654161.0
16,2017-04-26,874.23,876.0500,867.7481,871.624,1188464.0,0.0,1.0,874.23,876.0500,867.7481,871.624,1188464.0
17,2017-04-27,873.60,875.4000,870.3800,874.250,1734197.0,0.0,1.0,873.60,875.4000,870.3800,874.250,1734197.0
18,2017-04-28,910.66,916.8500,905.7700,905.960,3160585.0,0.0,1.0,910.66,916.8500,905.7700,905.960,3160585.0

In [226]:
def makegraph(asymbol, symboldf):
    sf = figure(title='Stock Price for '+'GOOG'+' during April 2017')
    sf.xaxis.axis_label = 'April 2017'
    sf.yaxis.axis_label = 'Closing Price'
    sf.line(x=np.array(dfreset['Date'].values, dtype=np.datetime64), y=np.array(dfreset['Close'].values),line_width=2, legend='Close')
    return sf

In [227]:
@app.route('/stockgraph', methods=['POST'])
def stockgraph():
    app.vars['stocksymbol'] = request.form['stocksymbol']
    script, div = components(sf)
    return render_template('stockgraph.html', script=script, div=div)